networks:
  demo:
    driver: bridge

services:

  postgres:
    extends:
      file: docker-compose.sql.yml
      service: postgres

  pgweb:
    extends:
      file: docker-compose.sql.yml
      service: pgweb


  mongodb:
    extends:
      file: docker-compose.nosql.yml
      service: mongodb

  mongo-express:
    extends:
      file: docker-compose.nosql.yml
      service: mongo-express
